# College Athletics Data Cleaning

## Library Dependencies

In order to run the below code and obtain the same results, certain library dependencies may be required to be downloaded first. The following libraries can be download by copying them into a blank code chunk and running the cell or running the commands through the terminal.

- %pip install pandas

## Imports

In [2]:
import pandas as pd
import recordlinkage as rl

## Data

In [3]:
df_athletics = pd.read_csv("instLevel.csv")
df_athletics.head()

,unitid,opeid,institution_name,addr1_txt,addr2_txt,city,state,zip,ClassificationCode,classification_name,...,IL_TOTAL_EXP_COED,IL_EXPENSE_MENALL,IL_EXPENSE_WOMENALL,IL_TOTAL_EXPENSE_ALL,UNDUP_CT_PARTIC_MEN,UNDUP_CT_PARTIC_WOMEN,TOT_REVENUE_ALL_NOTALLOC,TOT_EXPENSE_ALL_NOTALLOC,GRND_TOTAL_REVENUE,GRND_TOTAL_EXPENSE
0,100654,100200,alabama a & m university,4900 Meridian Street,NaN,normal,AL,35762,2,NCAA Division I-FCS,...,NaN,886688,2451537,3338225,252,156,2054613,2740961,12639752,12639752
1,100663,105200,university of alabama at birmingham,Administration Bldg Suite 1070,NaN,birmingham,AL,35294-0110,1,NCAA Division I-FBS,...,245737.0,3376573,6490380,9866953,223,191,9067659,10429985,43271595,42655846
2,100706,105500,university of alabama in huntsville,301 Sparkman Dr,NaN,huntsville,AL,35899,5,NCAA Division II without football,...,NaN,2207816,2533025,4740841,222,162,2110989,2110989,8054352,8054352
3,100724,100500,alabama state university,915 S Jackson Street,NaN,montgomery,AL,36104-0271,2,NCAA Division I-FCS,...,NaN,1540242,2753360,4293602,227,151,3604955,3604955,14050365,14050365
4,100751,105100,the university of alabama,739 University Blvd,NaN,tuscaloosa,AL,35487-0100,1,NCAA Division I-FBS,...,NaN,14307726,24204112,38511838,314,334,49112632,71525942,243096720,243096720

In [4]:
df_athletics.shape

(2040, 169)

### Data Dictionary (Athletics)

- <b>unitid</b>: university ID

- <b>opeid</b>: Office of Postsecondary Education identification code

- <b>institution_name</b>: name of college or university

- <b>city</b>: City

- <b>state</b>: State Abbreviation

- <b>zip</b>: Zip Code

- <b>classification_name</b>: Division level of college athletics

- <b>EFTotalCount</b>: Total Athletes in the university

- <b>sector_name</b>: Public, Private, etc.

- <b>STUDENTAID_TOTAL</b>: Total Student Aid for all athletics teams

- <b>RECRUITEXP_TOTAL</b>: Total Recruiting expenses for all Athletics teams

- <b>GRND_TOTAL_REVENUE</b>: Grand Total Revenues

- <b>GRND_TOTAL_EXPENSE</b>: Grand Total Expenses

# Data Cleaning

Filter to only include the variables of interest identified earlier.

In [5]:
athletics_columns = ["unitid", "opeid", "institution_name", "city", "state", "zip", "classification_name", "institution_type", "institution_years", "EFTotalCount", "STUDENTAID_TOTAL", "RECRUITEXP_TOTAL", "GRND_TOTAL_REVENUE", "GRND_TOTAL_EXPENSE"]
df_athletics = df_athletics[athletics_columns]
df_athletics.head()

,unitid,opeid,institution_name,city,state,zip,classification_name,institution_type,institution_years,EFTotalCount,STUDENTAID_TOTAL,RECRUITEXP_TOTAL,GRND_TOTAL_REVENUE,GRND_TOTAL_EXPENSE
0,100654,100200,alabama a & m university,normal,AL,35762,NCAA Division I-FCS,public,4-year or above,5219,3654220,114085,12639752,12639752
1,100663,105200,university of alabama at birmingham,birmingham,AL,35294-0110,NCAA Division I-FBS,public,4-year or above,9805,8176953,789941,43271595,42655846
2,100706,105500,university of alabama in huntsville,huntsville,AL,35899,NCAA Division II without football,public,4-year or above,5642,2597502,58361,8054352,8054352
3,100724,100500,alabama state university,montgomery,AL,36104-0271,NCAA Division I-FCS,public,4-year or above,2959,4602765,214415,14050365,14050365
4,100751,105100,the university of alabama,tuscaloosa,AL,35487-0100,NCAA Division I-FBS,public,4-year or above,29956,15912938,7096598,243096720,243096720

In [6]:
df_athletics.dtypes

unitid                  int64
opeid                   int64
institution_name       object
city                   object
state                  object
zip                    object
classification_name    object
institution_type       object
institution_years      object
EFTotalCount            int64
STUDENTAID_TOTAL        int64
RECRUITEXP_TOTAL        int64
GRND_TOTAL_REVENUE      int64
GRND_TOTAL_EXPENSE      int64
dtype: object

In [7]:
df_athletics[df_athletics["state"].isna()]

,unitid,opeid,institution_name,city,state,zip,classification_name,institution_type,institution_years,EFTotalCount,STUDENTAID_TOTAL,RECRUITEXP_TOTAL,GRND_TOTAL_REVENUE,GRND_TOTAL_EXPENSE
2039,800001,844400,simon fraser university,burnaby,NaN,NaN,NCAA Division II without football,sector unknown,NaN,13096,990745,45501,5633553,5633553

In [8]:
df_athletics.to_csv("cleaned_athletics_data.csv")